name: Close GitHub and Jira issues on develop merge

on:
  pull_request:
    types: [closed]

permissions:
  issues: write

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check if merged into develop
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
        run: echo "✅ This PR was merged into develop"

      - name: Extract GitHub linked issues
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
        id: extract
        uses: peter-evans/linked-issues@v1

      - name: Close GitHub issues
        if: steps.extract.outputs.issues != ''
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.extract.outputs.issues }}

      - name: Extract Jira issue key from PR body
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
        id: extract-jira
        run: |
          JIRA_KEY=$(echo '${{ github.event.pull_request.body }}' | grep -oE '[A-Z]+-[0-9]+')
          echo "jira_key=$JIRA_KEY" >> $GITHUB_OUTPUT

      - name: Login to Jira
        if: steps.extract-jira.outputs.jira_key != ''
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Move Jira issue to Done
        if: steps.extract-jira.outputs.jira_key != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.extract-jira.outputs.jira_key }}
          transition: Done
